routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'QuestionController@blogQuestionList')->name('blog');

/*Route::get('/', function () {
    return view('blog');
})->name('blog');*/

Route::get('/login', function () {
    return view('login');
})->name('login');

Route::get('/register', function () {
    return view('register');
})->name('register');

Route::post('register', 'CustomAuthController@register');
Route::post('login', 'CustomAuthController@login');


Route::get('question/view/{id}', 'QuestionController@guestView')->name('guestView');

Route::get('question/edit/{id}', 'QuestionController@edit')->name('edit.question');

Route::post('question/edit/{id}', 'QuestionController@update')->name('update.question');

Route::post('question/delete/{id}', 'QuestionController@delete')->name('delete.question');

Route::get('question/like/{id}', 'QuestionController@likequestion');
Route::get('question/dislike/{id}', 'QuestionController@dislikequestion');


// Route::get('question/view/{id}', 'CommentController@viewcomment');

Route::post('question/view/{id}', 'CommentController@add')->name('addcomment');

Route::get('question/edit/comment/{id}', 'CommentController@edit')->name('editcomment');

Route::post('question/edit/comment/{id}', 'CommentController@update')->name('updatecomment');

Route::post('question/delete/comment/{id}', 'CommentController@delete')->name('deletecomment');

Route::get('category/question/view/{id}', 'QuestionController@categoryView')->name('categoryView');






Route::get('/about', function () {
    return view('about');
})->name('about');

Route::get('/contact', function () {
    return view('contactus');
})->name('contact');

Route::post('/contact', 'MessageController@add')->name('add');

Route::get('notification/read/{id}','HomeController@notificationview');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('socialauth/{provider}', 'SocialAuthController@redirectToProvider');
Route::get('socialauth/{provider}/callback', 'SocialAuthController@handleProviderCallback');


Route::get('/forgot', 'Auth\ForgotPasswordController@forgot')->name('forgot');

Route::get('/reset', 'Auth\ResetPasswordController@reset')->name('reset');


Route::get('/addquestion', 'QuestionController@addQuestion')->name('user.addquestion');







Route::group(['prefix'=>'user','middleware'=>'auth'], function(){
    Route::get('/profile', 'UserController@index')->name('user.profile');

    Route::get('/edit', 'UserController@edit')->name('user.edit');
    Route::post('/edit', 'UserController@update')->name('user.update');

    Route::get('/accountsetting', 'UserController@accountsetting')->name('user.accountsetting');
    Route::post('/accountsetting', 'UserController@account')->name('user.account');

    Route::get('/request', 'UserController@request')->name('user.request');
    // Route::get('/activities', 'UserController@activity')->name('user.activities');

    Route::get('profile/{id}', 'UserController@viewuser')->name('user.view');
    
    Route::post('/addquestion', 'QuestionController@storeQuestion')->name('question.storequestion');

   
    
    Route::get('/question', 'QuestionController@viewQuestionList')->name('user.questionlist');

    Route::get('/question/view/{id}', 'QuestionController@showQuestion')->name('user.viewquestion');

    Route::get('/question/edit/{id}', 'QuestionController@editQuestion')->name('user.editquestion');
    Route::post('/question/edit/{id}', 'QuestionController@updateQuestion')->name('question.updatequestion');
    
    Route::post('/question/delete/{id}', 'QuestionController@deleteQuestion')->name('question.delete');
    
    Route::get('/comment', 'CommentController@viewCommentlist')->name('user.commentlist');
    Route::get('/comment/view/{id}', 'CommentController@viewcomment')->name('user.viewcomment');

    Route::get('/comment/edit/{id}', 'CommentController@editcomment')->name('user.editcomment');

    Route::post('/comment/edit/{id}', 'CommentController@updatecomment')->name('user.updatecomment');

    Route::post('/comment/delete/{id}', 'CommentController@deletecomment')->name('comment.delete');
    

    Route::get('/notification', 'UserController@notification')->name('user.notification');
    
});



Route::get('/admin', 'AdminController@login')->name('admin.login');
Route::post('/admin', 'AdminAuthController@login');


Route::group(['prefix'=>'admin','middleware' => 'admin'], function(){
    




    Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');

    Route::get('/profile', 'AdminController@profile')->name('admin.profile');
    
    Route::get('/edit', 'AdminController@editprofile')->name('admin.edit');
    Route::post('/edit', 'AdminController@updateprofile')->name('admin.update');
    
    Route::get('/account', 'AdminController@account')->name('admin.account');
    Route::post('/account', 'AdminController@password')->name('admin.password');

    //alladmin

    Route::get('/admin', 'AdminController@alladmin')->name('admin.alladmin');
    Route::get('/admin/add', 'AdminController@addadmin')->name('admin.addadmin');
    Route::post('/admin/add', 'AdminController@add')->name('admin.add');

    Route::get('/admin/view/{id}', 'AdminController@viewadmin')->name('admin.viewadmin');

    Route::get('/admin/edit/{id}', 'AdminController@editadmin')->name('admin.editadmin');
    Route::post('/admin/edit/{id}', 'AdminController@updateadmin')->name('admin.updateadmin');

    Route::post('/admin/delete/{id}', 'AdminController@deleteAdmin')->name('admin.delete');
    
    //alluser

    Route::get('/user', 'AdminController@alluser')->name('admin.alluser');
    Route::get('/user/view/{id}', 'AdminController@viewuser')->name('admin.viewuser');
    Route::post('/user/delete/{id}', 'AdminController@deleteUser')->name('admin.deleteuser');
    Route::get('/user/ban/{id}', 'AdminController@banuser');
    Route::get('/user/unban/{id}', 'AdminController@unbanuser');
   

    // allcategory

    Route::resource('category', 'CategoryController');
    Route::post('/category/destroy/{id}','CategoryController@destroy');




   //allquestion

    Route::get('/question', 'AdminController@allquestion')->name('admin.question');
    Route::get('/question/view/{id}', 'AdminController@viewquestion')->name('admin.viewquestion');
    

    // allcomment

    Route::get('/comment', 'AdminController@allcomment')->name('admin.allcomment');
    Route::get('/comment/view', 'AdminController@viewcomment')->name('admin.viewcomment');


    // allmessage

    Route::get('/message', 'MessageController@index')->name('message');

    Route::get('/message/view/{id}', 'MessageController@view')->name('admin.viewmessage');
    Route::get('/message/reply/{id}', 'MessageController@reply')->name('admin.replymessage');

    Route::post('/message/delete/{id}','MessageController@delete')->name('admin.deletemessage');


    // add category
    //Route::get('/allcategory', 'AdminController@allcategory')->name('admin.allcategory');
    //Route::get('/allcategory/add', 'AdminController@addcategory')->name('admin.addcategory');





     //admin log-reg    

    // Route::get('/register', 'AdminController@register')->name('admin.register');
    // Route::post('/register', 'AdminAuthController@register');
});

resources/views/admin/addcategory.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || AddAdmin')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')
	<div class="container cnt">
		<div class="panel panel-default pnl">
			<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">Add Category</div>
			<div class="panel-body">
				<form action="{{ route('category.store') }}" method="post" >
					{{ csrf_field() }}
					
					<div class="col-md-4 col-md-offset-4">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-bars"></i></span>
									<input type="text" class="form-control" name="category"  placeholder="Enter category name..." required />
							
						</div>
						

						<br>
						<a class="btn btn-success" href="{{ route('category.index') }}">
								<i class="fa fa-undo"></i>
								Back
						</a>
						<input type="reset" name="cancel" value="Cancel" class="btn btn-danger">
						<input type="submit" name="addcategory" value="ADD" class="btn btn-info">
						

					</div>

					
					
				</form>
				
				

			</div>
		</div>


	</div>
@endsection

resources/views/admin/allcategory.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || All Category')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')

	<div class="container cnt">
			<div class="panel panel-default pnl">
		<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">
		    <b>All Category</b>	
		</div>
		
		<div class="panel-body">
			@include('section.msg')
			<div class="col-md-2 col-md-offset-8" style="margin-bottom: 10px;">
				
				<a href="{{ route('category.create') }}" class="btn btn-info category">Add Category</a>
			</div>
			<table class="table table-striped table-bordered bootstrap-datatable datatable responsive tbl">
				<thead>
					<tr>
						<th style="text-align: center;">Name</th>
						<th style="text-align: center;">Actions</th>
					</tr>
				</thead>
				<tbody>
					
					@foreach ( $categories as $key=>$category )
						<tr>
							<td>{{ $category->category_name }}</td>
							<td class="center">
								<a href="{{ route('category.edit',$category->id) }}" class="btn btn-warning"><i class="fa fa-pencil-square"></i> Edit</a>
								<form id="delete-from-{{ $category->id }}" action="/admin/category/destroy/{{ $category->id }}" style="display:none;" method="POST">
                                    {{ csrf_field() }}
                                                    
                                </form>
                                <button class="btn btn-danger" type="button" onclick="if(confirm('Are you sure? You want to delete this?')){
                                        event.preventDefault();
                                        document.getElementById('delete-from-{{ $category->id}}').submit();
                                            } else {
                                                event.preventDefault();
                                            }"><i class="fa fa-trash"></i> Delete
                                </button>
                                
							</td>
						</tr>
					@endforeach
				</tbody>
				<tbody>


					
				</tbody>
			</table>


		</div>
	</div>
	</div>
@endsection

resources/views/admin/allquestion.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || AllQuestion')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')
	<div class="container cnt">
			<div class="panel panel-default pnl">
		<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">
		    <b>Question List</b>	
		</div>
		
		<div class="panel-body">
			@include('section.msg')
			<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
				<thead>
					<tr>
						<th>SL No. </th>
						<th>Q provider </th>
						<th>Category </th>
						<th style="width: 250px;">Question Title</th>
						<th style="width: 250px;">Question Description</th>
						<th>Q Time</th>
						<th>Actions</th>
					</tr>
				</thead>

				<tbody>

					@foreach ($questions as $key => $question)
					<tr>
						<td>{{ $no++ }}</td>
						<td>{{ $question->user->name }}</td>
						<td>{{ $question->category->category_name }}</td>
						<td>{{ $question->title }}</td>
						<td>{{ $question->description }}</td>
						<td>{{ $question->created_at->diffForHumans() }}</td>
						<td class="center">
							<a class="btn btn-success" href="{{ route('admin.viewquestion', $question->id) }}">
								<i class="fa fa-eye icon-white"></i>
								View
							</a>
							
							<form id="delete-from-{{ $question->id }}" action="{{ route('question.delete', $question->id) }}" style="display:none;" method="POST">
                                {{ csrf_field() }}                        
                            </form>
                            
                            <button class="btn btn-danger" type="button" onclick="if(confirm('Are you sure? You want to delete this?')){
                                event.preventDefault();
                                document.getElementById('delete-from-{{ $question->id }}').submit();
                                }else {
                                	event.preventDefault();
                                }"><i class="fa fa-trash"></i> Delete
                            </button>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>


		</div>
	</div>
	</div>
@endsection

resources/views/admin/alluser.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || AllUser')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')

	<div class="container cnt">
			<div class="panel panel-default pnl">
		<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">
		    <b>All User</b>	
		</div>
		
		<div class="panel-body">
			@include('section.msg')
		
			<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
				<thead>
					<tr>
						<th>SL No.</th>
						<th>Name</th>
						<th>Email</th>
						<th>Status</th>
						<th>Registered</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>

					@foreach($users as $key=>$user)
					<tr>
						<td>{{ $no++ }}</td>
						<td>{{ $user->name }}</td>
						<td>{{ $user->email }}</td>
						@if($user->ban == 0)
						<td> Active </td>
						@else
						<td> Ban </td>
						@endif
						<td>{{ Carbon\Carbon::parse($user->created_at )->diffForHumans() }}</td>
						<td class="center">
							<a class="btn btn-success" href="{{ route('admin.viewuser', $user->id) }}">
								<i class="fa fa-eye icon-white"></i>
								View
							</a>
							@if($user->ban == 0)
							<a class="btn btn-warning" href="user/ban/{{ $user->id }}">
								<i class="fa fa-ban"></i>
								Ban
							</a>
							@else
							<a class="btn btn-warning" href="user/unban/{{  $user->id }}">
								<i class="fa fa-ban"></i>
								Unban
							</a>
							@endif
							<form id="delete-from-{{ $user->id }}" action="{{ route('admin.deleteuser', $user->id) }}" style="display:none;" method="POST">
                                {{ csrf_field() }}                        
                            </form>
                            
                            <button class="btn btn-danger" type="button" onclick="if(confirm('Are you sure? You want to delete this?')){
                                event.preventDefault();
                                document.getElementById('delete-from-{{ $user->id }}').submit();
                                }else {
                                	event.preventDefault();
                                }"><i class="fa fa-trash"></i> Delete
                            </button>
						   
						</td>
					</tr>
					@endforeach

				</tbody>
			</table>


		</div>
	</div>
	</div>
@endsection

resources/views/admin/banuser.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || BanUsers')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')

	<div class="container cnt">
		<div class="panel panel-default pnl">
		<div class="panel-heading"style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">
		    <b>Ban Users</b>	
		</div>
			<div class="panel-body">
			<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
						<th>Registered</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>


					<tr>
						<td>Kongkon Purkayestha</td>
						<td>kpurkayestha@gmail.com</td>
						<td>5 hr ago</td>
						<td class="center">
						   <a class="btn btn-success" href="#">
								<i class="fa fa-check"></i>
								Unblock
							</a>
						</td>
					</tr>

				</tbody>
				<tbody>


					<tr>
						<td>Kollol Purkayestha</td>
						<td>kollolp@gmail.com</td>
						<td>1 hr ago</td>
						<td class="center">
						    <a class="btn btn-success" href="#">
								<i class="fa fa-check"></i>
								Unblock
							</a>
						</td>
					</tr>

				</tbody>
			</table>


		</div>
	</div>
	</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || ViewUser')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')
<div class="container cnt">
		<div class="panel panel-default pnl">
			<div class="panel-heading" style="color:#fff;text-align: center; font-size: 20px; background-color: #343D46;">Website Overview</div>
			<div class="panel-body">
				<div class="panel-body">
					<div class="col-md-3">
						<div class="well dash-box">
							<h2><span class="fa fa-user" aria-hidden="true"></span> 203</h2>
							<h4>Users</h4>
						</div>
					</div>
					<div class="col-md-3">
						<div class="well dash-box">
							<h2><span class="fa fa-list-alt" aria-hidden="true"></span> 12</h2>
							<h4>Pages</h4>
						</div>
					</div>
					<div class="col-md-3">
						<div class="well dash-box">
							<h2><span class="fa fa-pencil" aria-hidden="true"></span> 33</h2>
							<h4>Posts</h4>
						</div>
					</div>
					<div class="col-md-3">
						<div class="well dash-box">
							<h2><span class="fa fa-bar-chart" aria-hidden="true"></span> 12,334</h2>
							<h4>Visitors</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/admin/editcategory.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || Edit Category')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')
	<div class="container cnt">
		<div class="panel panel-default pnl">
			<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">Edit Category</div>
			<div class="panel-body">
				<form action="{{ route('category.update', $category->id) }}" method="post" >
					{{ csrf_field() }}
					{{ method_field('PUT') }}
					<div class="col-md-4 col-md-offset-4">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-bars"></i></span>
									<input type="text" class="form-control" name="category"  placeholder="Enter category name..." value="{{ $category->category_name }}" required />
							
						</div>
						

						<br>
						<a class="btn btn-success" href="{{ URL::previous() }}">
								<i class="fa fa-undo"></i>
								Back
						</a>
						<input type="reset" name="cancel" value="Cancel" class="btn btn-danger">
						<input type="submit" name="save" value="Save" class="btn btn-info">
						

					</div>

					
					
				</form>
				
				

			</div>
		</div>


	</div>
@endsection

resources/views/admin/editprofile.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || EditProfile')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')
	
	<div class="container cnt">
		<div class="panel panel-default pnl">
			<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">Edit Profile</div>
			<div class="panel-body">

				@include('section.msg')

				<form action="{{ route('admin.update') }}" method="post" enctype="multipart/form-data">

					{{ csrf_field() }}

					<div class="col-md-4">
						<label><i class="fa fa-picture-o" aria-hidden="true"></i>
 						Upload a picture:</label>
						<input type="file" name="image" class="form-control" placeholder="choose a picture">
						<label><i class="fa fa-info-circle"></i>
							About yourself:</label>
						<textarea cols="40" rows="5" name="about" class="form-control">{{ Auth::user()->about }}</textarea>	
					</div>

					<div class="col-md-6">
						<label><i class="fa fa-user-circle"></i> Name:</label>
						<input type="text" name="name" value="{{ Auth::user()->name }}" class="form-control" required>
					
						<label><i class="fa fa-envelope"></i> Email:</label>
						<input type="email" name="email" value="{{ Auth::user()->email }}" class="form-control" disabled>

						<label><i class="fa fa-map-marker"></i> Location:</label>
						<input type="text" name="location" value="{{ Auth::user()->location }}" class="form-control"><br>

						<input type="reset" name="cancel" value="Cancel" class="btn btn-danger">
						<input type="submit" name="update" value="Update" class="btn btn-success">
					</div>
				</form>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.auth')

@section('title', 'AskMe || Admin Login')



@section('content')
	<div class="container">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default" style="margin-top: 150px;">
				<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;"> Admin Login </div>
				<div class="panel-body">
					@if (\Session::has('error'))
					    <div class="alert alert-danger">
					        <ul>
					            {!! \Session::get('error') !!}
					        </ul>
					    </div>
					@endif
					@if(count($errors) > 0)
						@foreach($errors->all() as $error)
						<h5>{{  $error  }}</h5>
						@endforeach
					@endif
					<form action="{{ route('admin.login') }}" method="post" class="form-horizontal">
						{{ csrf_field() }}
						
						<div class="form-group">
							<div class="col-md-8 col-md-offset-2">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" class="form-control" name="email"  placeholder="Enter your email" required />
								</div>
								{{-- @if ($errors->has('email'))
	                                    <span class="help-block">
	                                        <strong>{{ $errors->first('email') }}</strong>
	                                    </span>
                                	@endif --}}
							</div>
							
						</div>

						<div class="form-group">
							<div class="col-md-8 col-md-offset-2">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-key"></i></span>
									<input type="password" class="form-control" name="password"   placeholder="Enter your password" required/>
								</div>
								{{-- @if ($errors->has('password'))
	                                    <span class="help-block">
	                                        <strong>{{ $errors->first('password') }}</strong>
	                                    </span>
                                	@endif --}}
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-8 col-md-offset-4">
								<div class="checkbox">
									<label><input type="checkbox"> Remember me</label>
								</div>
							</div>
						</div>


						<div class="form-group">
							<div class="col-md-8 col-md-offset-4">
								<input class="btn btn-danger" type="reset" name="cancel" value="Cancel">
								<input class="btn btn-info" type="submit" name="login" value="Login">
							</div>


						</div>

					

				</form>
				
			</div>
		</div>

</div>

	</div>
@endsection
	

resources/views/admin/profile.blade.php
@extends('layouts.admin')

@section('title', 'AskMe || Profile')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/admin_nav.css') }}">

	<link rel="stylesheet" type="text/css" href="{{ asset('css/admin_allcss.css') }}">
@endpush

@section('content')

	<div class="container cnt">
		<div class="panel panel-default pnl">
			<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;">Profile</div>
			<div class="panel-body">
				@include('section.msg')
				<div class="col-md-4">
					<img src="{{ asset('uploads/admin/images/'.Auth::user()->pro_pic) }}" alt="profile.png" title="profile.png" class="profile-img">
					<div class="info">
						<h5>{{ Auth::user()->about }}</h5>
					</div>
					
				</div>

				<div class="col-md-8">
					<h1><img src="{{ asset('uploads/images/test.jpg') }}" alt="profile.png" class="icon-img">
 						{{ Auth::user()->name }}</h1>
				<h3><i class="fa fa-envelope" aria-hidden="true"></i>
				{{ Auth::user()->email }}</h3>
				<h4><i class="fa fa-map-marker" aria-hidden="true"></i>
				{{ Auth::user()->location }}</h4>
				<h4><i class="fa fa-history" aria-hidden="true"></i>
				{{ Auth::user()->created_at->diffForHumans() }}</h4>
				<h4><i class="fa fa-eye" aria-hidden="true"></i>
				0 profile views</h4>
				<h4><i class="fa fa-clock-o" aria-hidden="true"></i> Last seen 1 minute ago</h4>
				
				</div>
				
				

			</div>
		</div>


	</div>
@endsection

resources/views/admin/register.blade.php
@extends('layouts.auth')

@section('title', 'AskMe || Admin Register')


@section('content')
	<div class="container">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default" style="margin-top: 100px;">
				<div class="panel-heading" style="text-align: center; font-size: 20px; background-color: #343D46; color: #ffffff;"> Admin Register </div>
				<div class="panel-body" style="margin-top: 35px;">
				     
					<form action="{{ route('admin.register') }}" method="post" class="form-horizontal">
						{{ csrf_field() }}
							<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
							<div class="col-md-8 col-md-offset-2">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-user"></i></span>
									<input type="text" class="form-control" name="name"  placeholder="Enter your name" required />
								</div>
								@if ($errors->has('name'))
	                                    <span class="help-block">
	                                        <strong>{{ $errors->first('name') }}</strong>
	                                    </span>
                                	@endif
							</div>

							
						</div>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<div class="col-md-8 col-md-offset-2">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" class="form-control" name="email"  placeholder="Enter your email" required />
								</div>
								@if ($errors->has('email'))
	                                    <span class="help-block">
	                                        <strong>{{ $errors->first('email') }}</strong>
	                                    </span>
                                	@endif
							</div>
							
						</div>

						<div class="form-group{{ $errors->has('role') ? ' has-error' : '' }}">
							<div class="col-md-8 col-md-offset-2">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-bars"></i></span>
									<select class="form-control" name="role" required>
										<option value="">Role</option>
										<option value="Admin">Admin</option>
							
									</select>
								</div>
								@if ($errors->has('role'))
	                                <span class="help-block">
	                                    <strong>{{ $errors->first('role') }}</strong>
	                                </span>
                                @endif
							</div>
						</div>

						<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
							<div class="col-md-8 col-md-offset-2">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-key"></i></span>
									<input type="password" class="form-control" name="password"   placeholder="Enter your password" required/>
								</div>
								@if ($errors->has('password'))
	                                <span class="help-block">
	                                    <strong>{{ $errors->first('password') }}</strong>
	                                </span>
                                @endif
							</div>
						</div>
						
							

						<div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
							<div class="col-md-8 col-md-offset-2">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-key"></i></span>
									<input type="password" class="form-control" name="password_confirmation"   placeholder="Re enter your password" required/>
								</div>
								@if ($errors->has('password_confirmation'))
	                                <span class="help-block">
	                                    <strong>{{ $errors->first('password_confirmation') }}</strong>
	                                </span>
                              	@endif
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-8 col-md-offset-4">
								<input class="btn btn-danger" type="reset" name="cancel" value="Cancel">
								<input class="btn btn-info" type="submit" name="register" value="Register">
							</div>


						</div>
					

				</form>
				
			</div>
		</div>

</div>

	</div>
@endsection